name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4        # v4 usa Node 20 en la propia acción
        with:
          node-version: 20                # usa 18 LTS o 20 ESTABLE; 22 aún es experimental

      - name: Install dependencies
        run: npm ci                       # más fiable que bahmutov/npm-install

      - name: Build project
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4  # ←  CAMBIO v3 → v4
        with:
          name: production-files
          path: dist                      # sin ./, más limpio
          if-no-files-found: error        # falla si dist no existe

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # ←  CAMBIO v3 → v4
        with:
          name: production-files
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
